### PR TITLE
config: default view configuration

### PR DESCRIPTION
**Pull request by jmartinm**
* Allows configuration of template to be rendered by default for
  collection landing pages.

Signed-off-by: Javier Martin Montull <javier.martin.montull@cern.ch>

### CODE REVIEW

**Comment by egabancho** [comment]
Travis is failing because of Sphinx, could you please take a look at https://github.com/inveniosoftware/cookiecutter-invenio-module/commit/c8d93e4f06be8f329bb25ea69c19a53ffbcc980a?

**Comment by jmartinm** [comment]
> Travis is failing because of Sphinx, could you please take a look at inveniosoftware/cookiecutter-invenio-module@c8d93e4?

Done.

**Comment by egabancho** [comment]
LGTM, we'll see what travis says 😜

**Comment by jmartinm** [comment]
> LGTM, we'll see what travis says

It looked good to Mr. Travis too. Can you merge? Thanks

**Pull request merged**
