### PR TITLE
WIP global: update for ES5 migration

### PR DESCRIPTION
**Pull request by szymonlopaciuk**
Addresses #86

### CODE REVIEW

**Comment by lnielsen** [comment]
Thanks for the PR - have a look at https://inveniosoftware.org/blog/2017-12-01-invenio-sprint/ ("Adding Elasticsearch v5 support to a module"). There's a guide on how to add ES5 support which might be useful.

**Comment by lnielsen** [comment]
Also since Collections uses perculators, you might find inspiration in OAIServer: https://github.com/inveniosoftware/invenio-oaiserver/commit/62cfe13049a1ab054af83e8af8287733e3f254e8

**Comment by david-caro** [comment]
@lnielsen I'm a bit confused here about the test failures :/, locally I can't reproduce (es5/python2).

**Comment by david-caro** [comment]
I see... xd 
```
Elasticsearch requires at least Java 8 but your Java version from /usr/lib/jvm/java-7-oracle/bin/java does not meet this requirement
```

**Comment by david-caro** [comment]
hmpf, there's something fishy going on with the tests, by themselves work, but when running together they fail, I suspect that it's related with the cleanup but I'm not sure. Any input is appreciated.

**Comment by david-caro** [comment]
I'm suspicious about the signals, as it seems not to unregister them properly:
```python
(Pdb++) signals.before_record_insert.receivers
{140309335324944: <invenio_collections.receivers.CollectionUpdater object at 0x7f9c50173910>, 140309336330192: <invenio_collections.receivers.CollectionUpdater object at 0x7f9c50268fd0>, 140309325279440: <invenio_collections.receivers.CollectionUpdater object at 0x7f9c4f7df0d0>, 140309334003984: <invenio_collections.receivers.CollectionUpdater object at 0x7f9c50031110>, 140309327702672: <invenio_collections.receivers.CollectionUpdater object at 0x7f9c4fa2ea90>, 140309408487120: <invenio_collections.receivers.CollectionUpdater object at 0x7f9c547396d0>, 140309325279888: <invenio_collections.receivers.CollectionUpdater object at 0x7f9c4f7df290>}
```

It seems to be registered many many times.

**Comment by lnielsen** [comment]
Closing PR because it's been stale for a long time.

**Pull request closed without merging**
