### PR TITLE
models: add override column

### PR DESCRIPTION
**Pull request by jacquerie**
Here's what I meant in https://github.com/inveniosoftware/invenio-collections/issues/72#issuecomment-323555500: it's not the most elegant solution, but it's a pragmatic one.

~~Adding a new column requires a new Alembic recipe, which is still missing from this PR, but I wanted to have an external opinion before continuing.~~

### CODE REVIEW

**Comment by lnielsen** [comment]
I also fine with the solution in this PR, I just want to highlight a similar problem in OAIServer which may or may not work in this case (and I'm not sure how much work it would be to adapt the code).

In Invenio-OAIServer, for some OAI-PMH setspecs we just want to put them manually into ``_oai.sets`` and ensure the system doesn't mess them. Example is e.g. Zenodo, where we on publish time knows exactly which OAI sets a record belongs to based on community memberships, hence it's waste to have to wait for a async process to run a query and update the record with another revision when we already know the information upfront.

The way it works in OAIServer for a setspec you want to manage manually is that you simply set the dbquery to an empty string, and then the system won't mess with the set. If a record is in an OAI setspec it will stay there, if it's not there it won't be added. 

Regarding this PR, then the only thing I'm struggling a bit with is the name ``override`` that I don't think captures what the flag really means (or I don't understand the existing code, which is very likely :-))

**Comment by jacquerie** [comment]
> Regarding this PR, then the only thing I'm struggling a bit with is the name override that I don't think captures what the flag really means

I don't like either, but it's the best I could come up with while rubber ducking a colleague... What I meant to say is "skip checking if the record matches the query and assume that it does", not unlike your OAIServer use case. That is, I thought, "override" the query. I also thought about "skip", but didn't like it because you might think that it means "skip adding this collection", not "skip running this query". "skipmatch" is clearer, but quite awkward...

**Comment by tiborsimko** [comment]
@jacquerie What about `dbquery_skip` or `dbquery_skip_check` or `allow_dbquery_skip` or something along these lines? Or even `dbquery_override`? Sounds a bit more explicit in this way, so it would be probably enough to clear usage doubts here... However, seeing such a field getting introduced may still feel kinda weird... referring to your elegance vs pragmatism musings.

**Comment by jacquerie** [comment]
I like `dbquery_skip` !

> However, seeing such a field getting introduced may still feel kinda weird... referring to your elegance vs pragmatism musings.

Would you rather do something like
```python
for name, data in iteritems(collections):
        if data['query'] == '' or _build_query(data['query']).match(record):
            yield data['ancestors']
```
instead of
https://github.com/inveniosoftware/invenio-collections/blob/31054057494327556f1d3a7a334ee177f5617e1c/invenio_collections/receivers.py#L68-L70
?

**Comment by jacquerie** [comment]
Wait, that won't work! It would just add ALL the collections to ALL the records...

**Comment by jacquerie** [comment]
This proved to be too complicated to implement correctly and with the minimal impact in `invenio-collections` as possible, so we're going with the route outlined in https://github.com/inspirehep/inspire-dojson/pull/62.

**Pull request closed without merging**
